# Generated by Django 4.0.5 on 2022-07-10 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Article', '0003_likkes_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likkes',
            name='author',
        ),
        migrations.RemoveField(
            model_name='likkes',
            name='liked',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
        migrations.DeleteModel(
            name='Likkes',
        ),
    ]
