# Generated by Django 4.0.5 on 2022-07-12 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Article', '0005_comment_delete_comments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={},
        ),
    ]
