# Generated by Django 4.0.5 on 2022-07-16 02:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Article', '0008_image_alter_comment_options_alter_comment_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='post_like',
            field=models.ManyToManyField(related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
