# Generated by Django 4.0.5 on 2022-08-13 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Article', '0011_remove_bcd_posti_remove_bcd_user_delete_abc_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
