# Generated by Django 4.0.5 on 2022-07-08 20:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('author', models.CharField(max_length=150)),
                ('body', models.TextField()),
                ('publish', models.DateTimeField(default=datetime.datetime(2022, 7, 8, 20, 13, 8, 520812, tzinfo=utc))),
            ],
        ),
    ]
